name: Publish jar to the Maven
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USER }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-passphrase:  ${{ secrets.GPG_PASSWORD }}
      - name: Publish to Apache Maven Central
        run: mvn -P deploy -pl -generator deploy
