name: Publish jar to the Maven
on:
  release:
    types: [created]
# on:
#   push:
#     branches:
#       - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven package
        run: mvn -P ci -pl -generator clean package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
            gpg_private_key: ${{ secrets.GPG_SECRET }}
            gpg_passphrase: ${{ secrets.GPG_PASSWORD }}
            nexus_username: ${{ secrets.OSSRH_USER }}
            nexus_password: ${{ secrets.OSSRH_PASSWORD }}
